redmine/app/config/routes.rb
  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/twofa/confirm', :to => 'account#twofa_confirm', :via => :get
  match 'account/twofa/resend', :to => 'account#twofa_resend', :via => :post
  match 'account/twofa', :to => 'account#twofa', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get
  get 'account/activation_email', :to => 'account#activation_email', :as => 'activation_email'

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put, :patch]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put, :patch]
  match '/preview/text', :to => 'previews#text', :as => 'preview_text', :via => [:get, :post, :put, :patch]

  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Auto complate routes
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/wiki_pages/auto_complete', :to => 'auto_completes#wiki_pages', :via => :get, :as => 'auto_complete_wiki_pages'

  # Misc issue routes. TODO: move into resources
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  resources :journals, :only => [:edit, :update] do
    member do
      get 'diff'
    end
  end

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  get   '/issues/imports/new', :to => 'imports#new',
        :defaults => {:type => 'IssueImport'}, :as => 'new_issues_import'
  get   '/time_entries/imports/new', :to => 'imports#new',
        :defaults => {:type => 'TimeEntryImport'}, :as => 'new_time_entries_import'
  get   '/users/imports/new', :to => 'imports#new',
        :defaults => {:type => 'UserImport'}, :as => 'new_users_import'
  post  '/imports', :to => 'imports#create', :as => 'imports'
  get   '/imports/:id', :to => 'imports#show', :as => 'import'
  match '/imports/:id/settings', :to => 'imports#settings', :via => [:get, :post], :as => 'import_settings'
  match '/imports/:id/mapping', :to => 'imports#mapping', :via => [:get, :post], :as => 'import_mapping'
  match '/imports/:id/run', :to => 'imports#run', :via => [:get, :post], :as => 'import_run'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :put]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  post 'my/page', :to => 'my#update_page'
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  get 'my/api_key', :to => 'my#show_api_key', :as => 'my_api_key'
  post 'my/api_key', :to => 'my#reset_api_key'
  post 'my/rss_key', :to => 'my#reset_rss_key', :as => 'my_rss_key'
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post
  match 'my/twofa/activate/init', :controller => 'twofa', :action => 'activate_init', :via => :post
  match 'my/twofa/:scheme/activate/init', :controller => 'twofa', :action => 'activate_init', :via => :post
  match 'my/twofa/:scheme/activate/confirm', :controller => 'twofa', :action => 'activate_confirm', :via => :get
  match 'my/twofa/:scheme/activate', :controller => 'twofa', :action => 'activate', :via => [:get, :post]
  match 'my/twofa/:scheme/deactivate/init', :controller => 'twofa', :action => 'deactivate_init', :via => :post
  match 'my/twofa/:scheme/deactivate/confirm', :controller => 'twofa', :action => 'deactivate_confirm', :via => :get
  match 'my/twofa/:scheme/deactivate', :controller => 'twofa', :action => 'deactivate', :via => [:get, :post]
  match 'my/twofa/select_scheme', :controller => 'twofa', :action => 'select_scheme', :via => :get
  match 'my/twofa/backup_codes/init', :controller => 'twofa_backup_codes', :action => 'init', :via => :post
  match 'my/twofa/backup_codes/confirm', :controller => 'twofa_backup_codes', :action => 'confirm', :via => :get
  match 'my/twofa/backup_codes/create', :controller => 'twofa_backup_codes', :action => 'create', :via => [:get, :post]
  match 'my/twofa/backup_codes', :controller => 'twofa_backup_codes', :action => 'show', :via => [:get]
  match 'users/:user_id/twofa/deactivate', :controller => 'twofa', :action => 'admin_deactivate', :via => :post

  resources :users do
    resources :memberships, :controller => 'principal_memberships'
    resources :email_addresses, :only => [:index, :create, :update, :destroy]
  end

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new', :as => 'new_watchers'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    collection do
      get 'autocomplete'
    end

    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
      match 'bookmark', :via => [:delete, :post]
    end

    shallow do
      resources :memberships, :controller => 'members' do
        collection do
          get 'autocomplete'
        end
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create]
    # Used when updating the form of a new issue
    post 'issues/new', :to => 'issues#new'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    shallow do
      resources :issue_categories
    end
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end

    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
      get 'tab/:name', :action => 'issue_tab', :as => 'tab'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
    end

redmine/app/app/helpers/users_helper.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-2021  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module UsersHelper
  include ApplicationHelper

  def users_status_options_for_select(selected)
    user_count_by_status = User.group('status').count.to_hash
    options_for_select([[l(:label_all), '']] + (User.valid_statuses.map {|c| ["#{l('status_' + User::LABEL_BY_STATUS[c])} (#{user_count_by_status[c].to_i})", c]}), selected.to_s)
  end

  def user_mail_notification_options(user)
    user.valid_notification_options.collect {|o| [l(o.last), o.first]}
  end

  def textarea_font_options
    [[l(:label_font_default), '']] + UserPreference::TEXTAREA_FONT_OPTIONS.map {|o| [l("label_font_#{o}"), o]}
  end

  def history_default_tab_options
    [[l('label_issue_history_notes'), 'notes'],
     [l('label_history'), 'history'],
     [l('label_issue_history_properties'), 'properties'],
     [l('label_time_entry_plural'), 'time_entries'],
     [l('label_associated_revisions'), 'changesets'],
     [l('label_last_tab_visited'), 'last_tab_visited']]
  end

  def change_status_link(user)
    url = {:controller => 'users', :action => 'update', :id => user, :page => params[:page], :status => params[:status], :tab => nil}

    if user.locked?
      link_to l(:button_unlock), url.merge(:user => {:status => User::STATUS_ACTIVE}), :method => :put, :class => 'icon icon-unlock'
    elsif user.registered?
      link_to l(:button_activate), url.merge(:user => {:status => User::STATUS_ACTIVE}), :method => :put, :class => 'icon icon-unlock'
    elsif user != User.current
      link_to l(:button_lock), url.merge(:user => {:status => User::STATUS_LOCKED}), :method => :put, :class => 'icon icon-lock'
    end
  end

  def additional_emails_link(user)
    if user.email_addresses.count > 1 || Setting.max_additional_emails.to_i > 0
      link_to l(:label_email_address_plural), user_email_addresses_path(@user), :class => 'icon icon-email-add', :remote => true
    end
  end

  def user_emails(user)
    emails = [user.mail]
    emails += user.email_addresses.order(:id).where(:is_default => false).pluck(:address)
    emails.map {|email| mail_to(email, nil)}.join(', ').html_safe
  end

  def user_settings_tabs
    tabs =
      [
        {:name => 'general', :partial => 'users/general', :label => :label_general},
        {:name => 'memberships', :partial => 'users/memberships', :label => :label_project_plural}
      ]
    if Group.givable.any?
      tabs.insert 1, {:name => 'groups', :partial => 'users/groups', :label => :label_group_plural}
    end
    tabs
  end

  def csv_content(column_name, user)
    case column_name
    when 'status'
      l("status_#{User::LABEL_BY_STATUS[user.status]}")
    when 'twofa_scheme'
      if user.twofa_active?
        l("twofa__#{user.twofa_scheme}__name")
      else
        l(:label_disabled)
      end
    else
      user.send(column_name)
    end
  end

  def users_to_csv(users)
    Redmine::Export::CSV.generate(:encoding => params[:encoding]) do |csv|
      columns = [
        'login',
        'firstname',
        'lastname',
        'mail',
        'admin',
        'status',
        'twofa_scheme',
        'created_on',
        'updated_on',
        'last_login_on',
        'passwd_changed_on'
      ]
      user_custom_fields = UserCustomField.sorted

      # csv header fields
      csv << columns.map {|column| l('field_' + column)} + user_custom_fields.pluck(:name)
      # csv lines
      users = users.preload(:custom_values)
      users.each do |user|
        values = columns.map {|c| csv_content(c, user)} +
                 user_custom_fields.map {|custom_field| user.custom_value_for(custom_field)}

        csv << values.map do |value|
          format_object(value, false) do |v|
            case v.class.name
            when 'Float'
              sprintf('%.2f', v).gsub('.', l(:general_csv_decimal_separator))
            else
              v
            end
          end
        end
      end
    end
  end
end

redmine/app/app/views/users/_general.html.erb
<%= labelled_form_for @user, :html => {:multipart => true} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <% if @user.active? && email_delivery_enabled? && @user != User.current -%>
    <p><label><%= check_box_tag 'send_information', 1, params[:send_information] %> <%= l(:label_send_information) %></label></p>
  <% end -%>
  <p><%= submit_tag l(:button_save) %></p>
<% end %>

redmine/app/app/views/users/_memberships.html.erb
<%= render_principal_memberships @user %>

redmine/app/app/views/users/destroy.html.erb
<%= title l(:label_confirmation) %>

<%= form_tag user_path(@user), method: :delete do %>
<div class="warning">
  <p><strong><%= @user.name %> (<%= @user.login %>)</strong></p>

  <p><%= l :text_user_destroy_confirmation, login: @user.login %></p>

  <p>
    <label for="confirm"><%= l :field_login %></label>
    <%= text_field_tag 'confirm' %>
  </p>
</div>

<p>
  <%= submit_tag l(:button_delete) %>
  <%= submit_tag l(:button_lock), name: 'lock' unless @user.locked? %>
  <%= link_to l(:button_cancel), users_path %>
</p>
<% end %>

redmine/app/app/views/users/destroy_membership.js.erb
$('#tab-content-memberships').html('<%= escape_javascript(render :partial => 'users/memberships') %>');

redmine/app/app/views/users/edit.html.erb
<div class="contextual">
<%= link_to l(:label_profile), user_path(@user), :class => 'icon icon-user' %>
<%= additional_emails_link(@user) %>
<%= change_status_link(@user) %>
<%= delete_link user_path(@user) if User.current != @user %>
</div>

<%=
  page_title = title [l(:label_user_plural), users_path], @user.login
  page_title.insert(page_title.rindex(' ') + 1, avatar(@user).to_s)
%>

<%= render_tabs user_settings_tabs %>

redmine/app/app/views/users/index.html.erb
<div class="contextual">
<%= link_to l(:label_user_new), new_user_path, :class => 'icon icon-add' %>
  <%= actions_dropdown do %>
    <% if User.current.allowed_to?(:import_users, nil, :global => true) %>
      <%= link_to l(:button_import), new_users_import_path, :class => 'icon icon-import' %>
    <% end %>
  <% end %>
</div>

<h2><%=l(:label_user_plural)%></h2>

<%= form_tag(users_path, { :method => :get, :id => 'users_form' }) do %>
<fieldset><legend><%= l(:label_filter_plural) %></legend>
<label for='status'><%= l(:field_status) %>:</label>
<%= select_tag 'status', users_status_options_for_select(@status), :class => "small", :onchange => "this.form.submit(); return false;"  %>

<% if @groups.present? %>
<label for='group_id'><%= l(:label_group) %>:</label>
<%= select_tag 'group_id', content_tag('option') + options_from_collection_for_select(@groups, :id, :name, params[:group_id].to_i), :onchange => "this.form.submit(); return false;"  %>
<% end %>

<label for='name'><%= l(:label_user) %>:</label>
<%= text_field_tag 'name', params[:name], :size => 30 %>
<%= submit_tag l(:button_apply), :class => "small", :name => nil %>
<%= link_to l(:button_clear), users_path, :class => 'icon icon-reload' %>
</fieldset>
<%= hidden_field_tag 'encoding', l(:general_csv_encoding) unless l(:general_csv_encoding).casecmp('UTF-8') == 0 %>
<% end %>
&nbsp;

<% if @users.any? %>
<div class="autoscroll">
<table class="list users">
  <thead><tr>
  <%= sort_header_tag('login', :caption => l(:field_login)) %>
  <%= sort_header_tag('firstname', :caption => l(:field_firstname)) %>
  <%= sort_header_tag('lastname', :caption => l(:field_lastname)) %>
  <th><%= l(:field_mail) %></th>
  <%= sort_header_tag('admin', :caption => l(:field_admin), :default_order => 'desc') %>
  <%= sort_header_tag('created_on', :caption => l(:field_created_on), :default_order => 'desc') %>
  <%= sort_header_tag('last_login_on', :caption => l(:field_last_login_on), :default_order => 'desc') %>
    <th></th>
  </tr></thead>
  <tbody>
<% for user in @users -%>
  <tr class="<%= user.css_classes %>">
  <td class="username"><%= avatar(user, :size => "14") %><%= link_to user.login, edit_user_path(user) %></td>
  <td class="firstname"><%= user.firstname %></td>
  <td class="lastname"><%= user.lastname %></td>
  <td class="email"><%= mail_to(user.mail) %></td>
  <td class="tick"><%= checked_image user.admin? %></td>
  <td class="created_on"><%= format_time(user.created_on) %></td>
  <td class="last_login_on"><%= format_time(user.last_login_on) unless user.last_login_on.nil? %></td>
    <td class="buttons">
      <%= change_status_link(user) %>
      <%= delete_link user_path(user, :back_url => request.original_fullpath), :data => {} unless User.current == user %>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>
<span class="pagination"><%= pagination_links_full @user_pages, @user_count %></span>
<% other_formats_links do |f| %>
  <%= f.link_to_with_query_parameters 'CSV', {}, :onclick => "showModal('csv-export-options', '330px'); return false;" %>
<% end %>
<div id="csv-export-options" style="display: none;">
  <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
  <%= export_csv_encoding_select_tag %>
  <p class="buttons">
    <%= submit_tag l(:button_export), :name => nil, :id => 'csv-export-button' %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => 'hideModal(this);', :type => 'button' %>
  </p>
</div>
<%= javascript_tag do %>
$(document).ready(function(){
  $('input#csv-export-button').click(function(){
    $('form input#encoding').val($('select#encoding option:selected').val());
    $('form#users_form').attr('action', "<%= users_path(:format => 'csv') %>").submit();
    $('form#users_form').attr('action', '<%= users_path %>');
    hideModal(this);
  });
});
<% end %>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% html_title(l(:label_user_plural)) -%>

redmine/app/app/views/users/new.html.erb
<%= title [l(:label_user_plural), users_path], l(:label_user_new) %>

<%= labelled_form_for @user, :html => {:multipart => true} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <% if email_delivery_enabled? %>
  <p><label><%= check_box_tag 'send_information', 1, params[:send_information] %> <%= l(:label_send_information) %></label></p>
  <% end %>
  <p>
    <%= submit_tag l(:button_create) %>
    <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
  </p>
<% end %>

<% if @auth_sources.present? && @auth_sources.any?(&:searchable?) %>
  <%= javascript_tag do %>
    observeAutocompleteField('user_login', '<%= escape_javascript autocomplete_for_new_user_auth_sources_path %>', {
      select: function(event, ui) {
        $('input#user_firstname').val(ui.item.firstname);
        $('input#user_lastname').val(ui.item.lastname);
        $('input#user_mail').val(ui.item.mail);
        $('select#user_auth_source_id option').each(function(){
          if ($(this).attr('value') == ui.item.auth_source_id) {
            $(this).prop('selected', true);
            $('select#user_auth_source_id').trigger('change');
          }
        });
      }
    });
  <% end %>
<% end %>

redmine/app/app/views/users/show.html.erb
<div class="contextual">
<%= link_to(l(:button_edit), edit_user_path(@user), :class => 'icon icon-edit') if User.current.admin? && @user.logged? %>
</div>

<h2><%= avatar @user, :size => "50" %> <%= @user.name %></h2>

<div class="splitcontent">
<div class="splitcontentleft">
<ul>
  <li><%=l(:field_login)%>: <%= @user.login %></li>
  <% unless @user.pref.hide_mail %>
    <li><%=l(:field_mail)%>: <%= user_emails(@user) %></li>
  <% end %>
  <% @user.visible_custom_field_values.each do |custom_value| %>
  <% if !custom_value.value.blank? %>
    <li class="<%= custom_value.custom_field.css_classes %>"><%= custom_value.custom_field.name %>: <%= show_value(custom_value) %></li>
  <% end %>
  <% end %>
    <li><%=l(:label_registered_on)%>: <%= format_date(@user.created_on) %></li>
  <% unless @user.last_login_on.nil? %>
    <li><%=l(:field_last_login_on)%>: <%= format_date(@user.last_login_on) %></li>
  <% end %>
</ul>

<h3><%=l(:label_issue_plural)%></h3>

<table class="list issue-report">
<thead>
  <tr>
    <th></th>
    <th><%=l(:label_open_issues_plural)%></th>
    <th><%=l(:label_closed_issues_plural)%></th>
    <th><%=l(:label_total)%></th>
  </tr>
</thead>
<tbody>
  <% assigned_to_ids = ([@user.id] + @user.group_ids).join("|") %>
  <% sort_cond = 'priority:desc,updated_on:desc' %>
  <tr>
    <td class="name">
      <%= link_to l(:label_assigned_issues),
        issues_path(:set_filter => 1, :assigned_to_id => assigned_to_ids, :sort => sort_cond) %>
    </td>
    <td>
      <%= link_to @issue_counts[:assigned][:open],
        issues_path(:set_filter => 1, :assigned_to_id => assigned_to_ids, :sort => sort_cond) %>
    </td>
    <td>
      <%= link_to @issue_counts[:assigned][:total] - @issue_counts[:assigned][:open],
        issues_path(:set_filter => 1, :status_id => 'c', :assigned_to_id => assigned_to_ids, :sort => sort_cond) %>
    </td>
    <td class="total">
      <%= link_to @issue_counts[:assigned][:total],
        issues_path(:set_filter => 1, :status_id => '*', :assigned_to_id => assigned_to_ids, :sort => sort_cond) %>
    </td>
  </tr>
  <tr>
    <td class="name">
      <%= link_to l(:label_reported_issues),
        issues_path(:set_filter => 1, :author_id => @user.id, :sort => sort_cond) %>
    </td>
    <td>
      <%= link_to @issue_counts[:reported][:open],
        issues_path(:set_filter => 1, :author_id => @user.id, :sort => sort_cond) %>
    </td>
    <td>
      <%= link_to @issue_counts[:reported][:total] - @issue_counts[:reported][:open],
        issues_path(:set_filter => 1, :status_id => 'c', :author_id => @user.id, :sort => sort_cond) %>
    </td>
    <td class="total">
      <%= link_to @issue_counts[:reported][:total],
        issues_path(:set_filter => 1, :status_id => '*', :author_id => @user.id, :sort => sort_cond) %>
    </td>
  </tr>
</tbody>
</table>

<% unless @memberships.empty? %>
<h3><%=l(:label_project_plural)%></h3>
<table class="list projects">
<thead>
  <tr>
    <th><%=l(:label_project)%></th>
    <th><%=l(:label_role_plural)%></th>
    <th><%=l(:label_registered_on)%></th>
  </tr>
</thead>
<tbody>
<% memberships_by_project = @memberships.group_by(&:project) %>
<% project_tree(memberships_by_project.keys, :init_level => true) do |project, level| %>
  <% membership = memberships_by_project[project].first %>
  <tr class="<%= project.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    <td class="name"><span><%= link_to_project(project) %></span></td>
    <td class="roles"><%= membership.roles.sort.collect(&:to_s).join(', ') %></td>
    <td><%= format_date(membership.created_on) %></td>
  </tr>
<% end %>
</tbody>
</table>
<% end %>

<% if (User.current == @user || User.current.admin?) && @user.groups.any? %>
<div id="groups">
  <h3><%=l(:label_group_plural)%></h3>
  <ul>
  <% for group in @user.groups %>
    <li><%= link_to_group(group) %>
  <% end %>
  </ul>
</div>
<% end %>

<%= call_hook :view_account_left_bottom, :user => @user %>
</div>

<div class="splitcontentright">

<% unless @events_by_day.empty? %>
<h3><%= link_to l(:label_activity), :controller => 'activities',
                :action => 'index', :id => nil, :user_id => @user,
                :from => @events_by_day.keys.first %></h3>
<%= render :partial => 'activities/activities', :locals => {:events_by_day => @events_by_day} %>

<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:controller => 'activities', :action => 'index', :id => nil, :user_id => @user, :key => User.current.rss_key} %>
<% end %>

<% content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom, :controller => 'activities', :action => 'index', :user_id => @user, :format => :atom, :key => User.current.rss_key) %>
<% end %>
<% end %>
<%= call_hook :view_account_right_bottom, :user => @user %>
</div>
</div>
<% html_title @user.name %>